### PR TITLE
Fixed the reply to sent message for the intended recipient

### PR DESCRIPTION
**Pull request by trenshaw88**
The correct recipient is now selected on the reply message feature when in the show blade on sent messages

### CODE REVIEW

**Comment by chenggavin** [comment]
Doesn't work for multiple recipients. Sorry.

**Comment by melanieps1** [comment]
This is amaazing!!!!!!

**Comment by melanieps1** [comment]
@trenshaw88 changes comments

**Comment by melanieps1** [comment]
If there are multiple recipients and I click "Reply" from a sent message, it still replies to only one recipient.  Maybe the Reply button shouldn't show in this case when there are multiple recipients?

Gavin, Rachel and I talked and think it should reply to the sender.. so yourself.

**Pull request merged**
